import { Sep1Currency } from '../types/sep1';

/**
 * Generates a SEP-1 compliant stellar.toml string from currency metadata.
 */
export const generateStellarToml = (currencies: Sep1Currency[]): string => {
  let toml = "# stellar.toml generated by Stellar Kit IDE\n\n";

  currencies.forEach((currency) => {
    toml += "[[CURRENCIES]]\n";
    if (currency.code) toml += `code = "${currency.code}"\n`;
    if (currency.name) toml += `name = "${currency.name}"\n`;
    if (currency.issuer) toml += `issuer = "${currency.issuer}"\n`;
    if (currency.contract_id) toml += `contract_id = "${currency.contract_id}"\n`;
    if (currency.display_precision !== undefined) toml += `display_precision = ${currency.display_precision}\n`;
    if (currency.anchor_asset_type) toml += `anchor_asset_type = "${currency.anchor_asset_type}"\n`;
    if (currency.desc) toml += `desc = "${currency.desc}"\n`;
    if (currency.image) toml += `image = "${currency.image}"\n`;
    if (currency.status) toml += `status = "${currency.status}"\n`;
    toml += "\n";
  });

  return toml.trim();
};

/**
 * Basic validation for SEP-1 Currency entries.
 */
export const validateCurrency = (currency: Sep1Currency): string[] => {
  const errors: string[] = [];
  if (!currency.code) errors.push("Asset Code is required.");
  if (currency.code && currency.code.length > 12) errors.push("Asset Code must be 12 characters or less.");
  if (currency.issuer && !currency.issuer.startsWith('G')) errors.push("Invalid Issuer address.");
  if (currency.contract_id && !currency.contract_id.startsWith('C')) errors.push("Invalid Contract ID.");
  
  return errors;
};